sudo: false
language: node_js
node_js:
- 10.15.0
install:
- npm install
script:
- npm run prepare

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

deploy:
  provider: npm
  email: mickael.bouchaud@gmail.com
  api_key:
    secure: DM+zIkucK7dGA7PKAw9M2P0FyjnmMp87wngJ88rzSrh+BECX3vKzx4Cb8n9Eay7oMQfWQD98zESqiCkEkWPIMZGQeRQIIrCRt6dJnVJrH3aeNyDeWOamvylYuNdp1QWjd5Qx/t/gmF4Zh02DPp/4J8DyztDyQU6EHmbv4L3OiXboUAdWYEjWkjwv1Srhh+YlIt358aSydgiQp7MocdJg1scWSoYs98V7VIMITcwpWD8tFowB0DJYvZq3zRRWjykgdO5vD0hEte4Bv5zwDc3YqFp+1X0YzZ9gLYp0+jj8N9Ta69g1bjt82iN1ZiXquqIpDqF3T6FsR+WT+fJE1tQkhV5QnGQBjn746MAV8OSfb/yfoxV6jlGPOOpO/uaN8NziWG0bhLP4jYEB3hfQ8c7y6MPRYIl9UJugqh9AYK4pdZ9qSNg32+FyR0AyIyiZ9AvWb/3sycSimf5K5ixO53SOJA675Chd2xK8kmqGtZlV2+ORMwDdP6nSuBDAq8tOJYkZ4eFE/RCko1gfNmPTGGdN3W8vR1R1W5i6q89MUa6N78Dg9LXf6jg4y+C/wy0dWnPHAqKV5mER9+kS+oLmlS6U0oWUlVzgAy8PoB+CEet3GDnHCYE5hLkewFtTF1bcuKfxMW9mhtH/eWvR94jlbR3/ENBXu34ASBHryjtGl7Sfj9g=
  on:
    tags: true
    repo: KoRiGaN/Vue2Leaflet
